# Generated by Django 3.1.1 on 2020-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warikanmodel',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='warikanmodel',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='warikanmodel',
            name='priority',
        ),
        migrations.AddField(
            model_name='warikanmodel',
            name='name',
            field=models.CharField(default='齋藤', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warikanmodel',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
