# Generated by Django 3.1.1 on 2020-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0003_auto_20201019_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warikanmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
