# Generated by Django 3.1.1 on 2020-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0005_membermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='name',
            new_name='membername',
        ),
    ]
